version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "M@sterk3y"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql

  usuarioapi:
    build:
      context: .
      dockerfile: ./API/UsuarioAPI/Dockerfile
    container_name: usuarioapi
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"

  agendaapi:
    build:
      context: .
      dockerfile: ./API/AgendaAPI/Dockerfile
    container_name: agendaapi
    depends_on:
      - sqlserver
    ports:
      - "8081:8081"

volumes:
  sqlserver_data: