apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  labels:
    app: sqlserver
spec:
  type: NodePort
  selector:
    app: sqlserver
  ports:
  - port: 1433       # Porta interna do SQL Server
    targetPort: 1433 # Porta no contêiner
    nodePort: 30002  # Porta mapeada no nó para acesso externo