apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarioapi-deployment
  labels:
    app: usuarioapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usuarioapi
  template:
    metadata:
      labels:
        app: usuarioapi
    spec:
      containers:
      - name: usuarioapi
        image: trickfx/usuarioapi:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi" 
            cpu: "250m"     
          limits:
            memory: "512Mi" 
            cpu: "500m" 
