// <auto-generated />
using System;
using AgendaAPI.Infrastructure.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendaAPI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250206041006_MigrationInicial")]
    partial class MigrationInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgendaAPI.Domain.Entities.Agenda.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("Disponibilidade")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HorarioFim")
                        .HasColumnType("time(0)");

                    b.Property<TimeSpan>("HorarioInicio")
                        .HasColumnType("time(0)");

                    b.Property<int>("IdMedico")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Horario", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
